# Generated by Django 3.0.3 on 2020-03-21 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_auto_20200321_1538'),
        ('shelter', '0002_auto_20191123_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shelter.Shelter'),
        ),
        migrations.DeleteModel(
            name='Cage',
        ),
    ]
