# Generated by Django 3.1.2 on 2021-01-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0006_remove_room_shelter'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
