# Generated by Django 3.1.2 on 2021-02-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0007_shelter_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
