# Generated by Django 3.2.14 on 2022-07-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0010_auto_20220602_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='test',
            field=models.BooleanField(default=True),
        ),
    ]
