# Generated by Django 3.2.14 on 2022-08-08 20:43

from django.db import migrations, models
import django.db.models.deletion
import shelter.models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0003_auto_20220808_1343'),
        ('shelter', '0011_shelter_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='incident',
            field=models.ForeignKey(default=shelter.models.test_incident, on_delete=django.db.models.deletion.CASCADE, to='incident.incident'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
