# Generated by Django 3.2.14 on 2022-08-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0013_test_to_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='test',
        ),
    ]
