# Generated by Django 3.2.14 on 2023-03-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0024_auto_20230201_1653'),
        ('shelter', '0016_auto_20230206_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='public',
        ),
        migrations.AddField(
            model_name='shelter',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='intakesummary',
            name='animals',
            field=models.ManyToManyField(blank=True, to='animals.Animal'),
        ),
    ]
