# Generated by Django 3.2.14 on 2023-12-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0017_auto_20230329_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
