"""
Django settings for shelterly project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import datetime
import os
import json
import boto3

try:
    with open('config/secrets.json') as f:
        secrets = json.loads(f.read())
        for item in secrets.items():
            os.environ[item[0]] = item[1]
except FileNotFoundError:
    print("No secrets file found. Environmental variables must be set elsewhere.")

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
ORGANIZATION = os.environ.get('ORGANIZATION')
INCIDENT_NAME = os.environ.get('INCIDENT_NAME')
SHELTERLY_VERSION = os.environ.get('SHELTERLY_VERSION')

DEBUG = True
# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = ['*']
AUTH_USER_MODEL = 'accounts.ShelterlyUser'

# AWS Config
credentials = boto3.Session().get_credentials()
if credentials:
    AWS_ACCESS_KEY_ID = credentials.access_key
    AWS_SECRET_ACCESS_KEY = credentials.secret_key

# Use to output emails in console.
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django_smtp_ssl.SSLEmailBackend'
EMAIL_HOST = 'email-smtp.us-west-2.amazonaws.com'
EMAIL_PORT = '465'
EMAIL_HOST_USER = os.environ.get('EMAIL_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASSWORD')
EMAIL_USE_SSL = True

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_filters',
    'corsheaders',
    'accounts',
    'animals',
    'evac',
    'hotline',
    'intake',
    'location',
    'people',
    'rest_framework',
    'knox',
    'django_rest_passwordreset',
    'shelter',
    'frontend',
    'ordered_model',
    'actstream',
    'drf_yasg',
    'silk'
]

ACTSTREAM_SETTINGS = {
    'FETCH_RELATIONS': True,
    'USE_PREFETCH': True,
}

MIDDLEWARE = [
    'silk.middleware.SilkyMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # 'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'wsgi.application'
SITE_ID = 1

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DATABASE_NAME'),
        'USER': os.environ.get('DATABASE_USER'),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD'),
        'HOST': os.environ.get('DATABASE_HOST'),
        'PORT': 5432,
    }
}


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_L10N = True

USE_TZ = True

SECURE_SSL_REDIRECT = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "frontend/build/static"),
    os.path.join(BASE_DIR, "frontend/src/static")
]

MEDIA_URL = '/media/'

if DEBUG:
    STATIC_ROOT=os.path.join(BASE_DIR, 'static')
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
else:
    #Static File Settings
    STATICFILES_STORAGE = 'custom_storage.StaticStorage'
    #Media File Settings
    DEFAULT_FILE_STORAGE = 'custom_storage.MediaStorage'
    #AWS Settings
    AWS_STORAGE_BUCKET_NAME = 'shelterly-files'
    AWS_S3_REGION_NAME = 'us-west-2'



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ('knox.auth.TokenAuthentication',),
    'USER_SERIALIZER': 'accounts.serializers.UserSerializer',
}

REST_KNOX = {
  'TOKEN_TTL': datetime.timedelta(hours=1),
  'USER_SERIALIZER': 'accounts.serializers.UserSerializer',
  'AUTO_REFRESH': True
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'django.db.backends': {
            'level': 'DEBUG',
            'handlers': [],
            'propagate': False
        }
    },
}
