# Generated by Django 2.1.7 on 2019-05-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evacreq',
            name='worker',
        ),
    ]
