# Generated by Django 3.0.4 on 2020-04-16 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_delete_teammember'),
        ('hotline', '0002_auto_20191208_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Person'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_servicerequest', to='people.Person'),
        ),
    ]
