# Generated by Django 2.1.7 on 2019-05-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0002_remove_evacreq_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evacreq',
            name='attended_to',
        ),
        migrations.RemoveField(
            model_name='evacreq',
            name='last_seen',
        ),
    ]
