# Generated by Django 3.0.3 on 2020-03-02 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20200302_0319'),
        ('hotline', '0002_auto_20191208_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='accessible',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='turn_around',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Person'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_servicerequest', to='people.Person'),
        ),
    ]
