# Generated by Django 3.0.4 on 2020-04-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0003_auto_20200413_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='forced_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='key_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='turn_around',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='verbal_permission',
            field=models.BooleanField(default=False),
        ),
    ]
