# Generated by Django 3.0.4 on 2020-05-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0004_auto_20200427_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='apartment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='directions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='outcome',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='owner_notification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='zip_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
