# Generated by Django 3.0.8 on 2020-08-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0005_auto_20200515_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('closed', 'Closed')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='apartment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='outcome',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='owner_notification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='zip_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
