# Generated by Django 3.1.2 on 2020-11-04 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20201104_1730'),
        ('hotline', '0006_auto_20200828_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='followup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_service_request', to='people.person'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporter_service_request', to='people.person'),
        ),
    ]
