# Generated by Django 3.1.2 on 2020-12-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20201104_1730'),
        ('hotline', '0009_auto_20201114_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='owner',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='owner',
            field=models.ManyToManyField(related_name='owner_service_request', to='people.Person'),
        ),
    ]
