# Generated by Django 3.1.2 on 2020-12-14 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20201104_1730'),
        ('animals', '0013_auto_20201213_1845'),
        ('hotline', '0010_auto_20201210_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitnote',
            name='owner_contacted',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='owner',
            field=models.ManyToManyField(blank=True, to='people.Person'),
        ),
        migrations.CreateModel(
            name='OwnerContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('notes', models.TextField()),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
            ],
        ),
    ]
