# Generated by Django 3.1 on 2021-01-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0011_auto_20201218_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='directions',
            field=models.TextField(blank=True),
        ),
    ]
