# Generated by Django 3.1.2 on 2021-01-18 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0012_auto_20210101_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitnote',
            name='owner_contacted',
        ),
    ]
