# Generated by Django 3.1.2 on 2021-02-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0013_remove_visitnote_owner_contacted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='owner',
            new_name='owners',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('closed', 'Closed'), ('canceled', 'Canceled')], default='open', max_length=10),
        ),
    ]
