# Generated by Django 3.1.2 on 2021-02-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0014_auto_20210202_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitnote',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
