# Generated by Django 3.1.2 on 2021-04-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_auto_20210420_1128'),
        ('hotline', '0015_auto_20210210_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitnote',
            options={'ordering': ['-date_completed']},
        ),
        migrations.RemoveField(
            model_name='visitnote',
            name='evac_assignment',
        ),
        migrations.RemoveField(
            model_name='visitnote',
            name='service_request',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='request', to='people.Person'),
        ),
    ]
