# Generated by Django 3.1.2 on 2021-10-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0016_auto_20210420_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='sip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='utl',
            field=models.BooleanField(default=False),
        ),
    ]
