# Generated by Django 3.1.2 on 2022-02-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0017_auto_20211030_0802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='priority',
            field=models.IntegerField(default=2),
        ),
    ]
