# Generated by Django 3.1.2 on 2022-06-18 19:25

from django.db import migrations, models
import django.db.models.deletion
import hotline.models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_auto_20220618_0459'),
        ('hotline', '0020_auto_20220602_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.incident'),
        ),
    ]
