# Generated by Django 3.2.14 on 2024-04-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0021_servicerequest_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='id_for_incident',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
