# Generated by Django 3.2.18 on 2024-10-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0024_auto_20240731_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='caltopo_feature_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
