# Generated by Django 3.2.14 on 2025-01-06 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotline', '0025_servicerequest_caltopo_feature_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequestNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.DateTimeField(auto_now_add=True, null=True)),
                ('urgent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, max_length=2500)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotline.servicerequest')),
            ],
            options={
                'ordering': ['-open'],
            },
        ),
    ]
