# Generated by Django 3.2.14 on 2025-04-03 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0026_servicerequestnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='followup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequestnote',
            name='service_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='hotline.servicerequest'),
        ),
    ]
