# Generated by Django 2.1.11 on 2019-11-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20191103_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(blank=True, choices=[('Reported', 'Reported'), ('Sheltered', 'Sheltered'), ('Sheltered In Place', 'Sheltered In Place'), ('Not Found', 'Not Found'), ('Rest In Peace', 'Rest In Peace')], default='Reported', max_length=20, null=True),
        ),
    ]
