# Generated by Django 2.1.7 on 2019-05-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20190425_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='tag_info',
            new_name='behavior_notes',
        ),
        migrations.AddField(
            model_name='animal',
            name='collared',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(blank=True, choices=[('REP', 'Reported'), ('SHL', 'Sheltered'), ('SIP', 'Sheltered In Place'), ('NFD', 'Not Found'), ('RIP', 'Rest In Peace')], max_length=3, null=True),
        ),
    ]
