# Generated by Django 2.1.7 on 2019-05-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_auto_20190508_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='attended_to',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='markings',
            field=models.CharField(blank=True, choices=[('merle', 'Merle'), ('tuxedo', 'Tuxedo'), ('harlequin', 'Harlequin'), ('spotted', 'Spotted'), ('speckled', 'Speckled'), ('brindle', 'Brindle'), ('saddle', 'Saddle'), ('sable', 'Sable'), ('hairless', 'Hairless')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='pcolor',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('blue', 'Blue'), ('brown', 'Brown'), ('cream', 'Cream/Taupe'), ('gold', 'Gold'), ('gray', 'Gray'), ('red', 'Red'), ('white', 'White'), ('yellow', 'Yellow')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='scolor',
            field=models.CharField(blank=True, choices=[('merle', 'Merle'), ('tuxedo', 'Tuxedo'), ('harlequin', 'Harlequin'), ('spotted', 'Spotted'), ('speckled', 'Speckled'), ('brindle', 'Brindle'), ('saddle', 'Saddle'), ('sable', 'Sable'), ('hairless', 'Hairless')], max_length=50, null=True),
        ),
    ]
