# Generated by Django 2.1.11 on 2019-12-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_auto_20191119_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.CharField(blank=True, choices=[('Youth', 'Youth (< 2 Years)'), ('Adult', 'Adult (2 - 8 Years)'), ('Elerly', 'Elderly (8+ Years)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown')], default='unknown', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='markings',
            field=models.CharField(blank=True, choices=[('brindle', 'Brindle'), ('hairless', 'Hairless'), ('harlequin', 'Harlequin'), ('merle', 'Merle'), ('sable', 'Sable'), ('saddle', 'Saddle'), ('speckled', 'Speckled'), ('spotted', 'Spotted'), ('tuxedo', 'Tuxedo'), ('bengal', 'Bengal'), ('bicolor', 'Bicolor'), ('calico', 'Calico'), ('colorpoint', 'Colorpoint'), ('hairless', 'Hairless'), ('solid', 'Solid'), ('tabby', 'Tabby'), ('tortoiseshell', 'Tortoiseshell')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='pcolor',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('blue', 'Blue'), ('brown', 'Brown'), ('cream', 'Cream/Taupe'), ('gold', 'Gold'), ('gray', 'Gray'), ('red', 'Red'), ('white', 'White'), ('yellow', 'Yellow'), ('black', 'Black'), ('caramel', 'Caramel'), ('chocolate', 'Chocolate'), ('cinnamon', 'Cinnamon'), ('grey', 'Grey'), ('orange', 'Orange'), ('white', 'White')], max_length=50, null=True, verbose_name='Primary Color'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='scolor',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('blue', 'Blue'), ('brown', 'Brown'), ('cream', 'Cream/Taupe'), ('gold', 'Gold'), ('gray', 'Gray'), ('red', 'Red'), ('white', 'White'), ('yellow', 'Yellow'), ('black', 'Black'), ('caramel', 'Caramel'), ('chocolate', 'Chocolate'), ('cinnamon', 'Cinnamon'), ('grey', 'Grey'), ('orange', 'Orange'), ('white', 'White')], max_length=50, null=True, verbose_name='Secondary Color'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='size',
            field=models.CharField(blank=True, choices=[('Small', 'Small (< 20 lbs)'), ('Medium', 'Medium (21 - 60 lbs)'), ('Large', 'Large (61 - 110 lbs)'), ('Giant', 'Giant (111+ lbs)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(blank=True, choices=[('REPORTED', 'REPORTED'), ('SHELTERED', 'SHELTERED'), ('SHELTERED IN PLACE', 'SHELTERED IN PLACE'), ('NOT FOUND', 'NOT FOUND'), ('REST IN PEACE', 'REST IN PEACE')], default='REPORTED', max_length=20, null=True),
        ),
    ]
