# Generated by Django 2.1.11 on 2019-12-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_auto_20191207_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Sporting Group', 'Sporting Group'), ('Working Group', 'Working Group'), ('Toy Group', 'Toy Group'), ('Herding Group', 'Hearding Group'), ('Hound Group', 'Hound Group'), ('Terrier Group', 'Terrier Group')], default='unknown', max_length=50, null=True),
        ),
    ]
