# Generated by Django 2.1.7 on 2019-08-29 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
        ('animals', '0004_auto_20190513_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='cage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shelter.Cage'),
        ),
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/animals'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='scolor',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('blue', 'Blue'), ('brown', 'Brown'), ('cream', 'Cream/Taupe'), ('gold', 'Gold'), ('gray', 'Gray'), ('red', 'Red'), ('white', 'White'), ('yellow', 'Yellow')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small ()'), ('M', 'Medium ()'), ('L', 'Large ()')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='state',
            field=models.CharField(blank=True, choices=[('AL', 'AL'), ('AK', 'AK'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('OH', 'OH'), ('OK', 'OK'), ('PA', 'PA'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('VA', 'VA'), ('VT', 'VT'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(blank=True, choices=[('REP', 'Reported'), ('SHL', 'Sheltered'), ('SIP', 'Sheltered In Place'), ('NFD', 'Not Found'), ('RIP', 'Rest In Peace')], default='REP', max_length=3, null=True),
        ),
    ]
