# Generated by Django 3.0.4 on 2020-05-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_auto_20200321_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='address',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='city',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='state',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='animal',
            name='aggressive',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('yes', 'Yes'), ('no', 'No')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='attended_to',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('yes', 'Yes'), ('no', 'No')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='behavior_notes',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='animal',
            name='collared',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('yes', 'Yes'), ('no', 'No')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='color_notes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='animal',
            name='confined',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('yes', 'Yes'), ('no', 'No')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='fixed',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('yes', 'Yes'), ('no', 'No')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='pcolor',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('black', 'Black'), ('blue', 'Blue'), ('brown', 'Brown'), ('tan', 'Tan'), ('brindle', 'Brindle'), ('cream', 'Cream/Taupe'), ('gold', 'Gold'), ('gray', 'Gray'), ('red', 'Red'), ('white', 'White'), ('yellow', 'Yellow'), ('black', 'Black'), ('caramel', 'Caramel'), ('chocolate', 'Chocolate'), ('cinnamon', 'Cinnamon'), ('grey', 'Grey'), ('orange', 'Orange'), ('white', 'White')], max_length=50, verbose_name='Primary Color'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='scolor',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('black', 'Black'), ('blue', 'Blue'), ('brown', 'Brown'), ('tan', 'Tan'), ('brindle', 'Brindle'), ('cream', 'Cream/Taupe'), ('gold', 'Gold'), ('gray', 'Gray'), ('red', 'Red'), ('white', 'White'), ('yellow', 'Yellow'), ('black', 'Black'), ('caramel', 'Caramel'), ('chocolate', 'Chocolate'), ('cinnamon', 'Cinnamon'), ('grey', 'Grey'), ('orange', 'Orange'), ('white', 'White')], max_length=50, verbose_name='Secondary Color'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.CharField(blank=True, choices=[('youth', 'Youth'), ('adult', 'Adult'), ('elderly', 'Elderly'), ('kitten', 'Kitten'), ('youth', 'Youth'), ('adult', 'Adult'), ('elderly', 'Elderly'), ('geriatric', 'Geriatric')], max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='size',
            field=models.CharField(blank=True, choices=[('small', 'Small (< 20 lbs)'), ('medium', 'Medium (21 - 60 lbs)'), ('large', 'Large (61 - 110 lbs)'), ('giant', 'Giant (111+ lbs)'), ('small', 'Small ( < 10 lbs)'), ('full', 'Full Size (10+ lbs)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'REPORTED'), ('ASSIGNED', 'ASSIGNED'), ('SHELTERED', 'SHELTERED'), ('SHELTERED IN PLACE', 'SHELTERED IN PLACE'), ('NOT FOUND', 'NOT FOUND'), ('REST IN PEACE', 'REST IN PEACE')], default='REPORTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(blank=True, choices=[('cat', 'Cat'), ('dog', 'Dog'), ('horse', 'Horse'), ('other', 'Other')], max_length=50),
        ),
    ]
