# Generated by Django 3.0.8 on 2020-09-10 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_auto_20200717_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='image',
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.CharField(blank=True, choices=[('youth', 'Youth'), ('adult', 'Adult'), ('elderly', 'Elderly'), ('kitten', 'Kitten'), ('youth', 'Youth'), ('adult', 'Adult'), ('elderly', 'Elderly'), ('geriatric', 'Geriatric'), ('young', 'Young'), ('adult', 'Adult'), ('elderly', 'Elderly'), ('young', 'Young'), ('adult', 'Adult'), ('elderly', 'Elderly')], max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='pcolor',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('black', 'Black'), ('blue', 'Blue'), ('brown', 'Brown'), ('tan', 'Tan'), ('brindle', 'Brindle'), ('cream', 'Cream/Taupe'), ('gold', 'Gold'), ('gray', 'Gray'), ('red', 'Red'), ('white', 'White'), ('yellow', 'Yellow'), ('black', 'Black'), ('caramel', 'Caramel'), ('chocolate', 'Chocolate'), ('cinnamon', 'Cinnamon'), ('grey', 'Grey'), ('orange', 'Orange'), ('white', 'White'), ('black', 'Black'), ('brown', 'Brown'), ('bay', 'Bay'), ('chestnut', 'Chestnut'), ('grey', 'Grey'), ('white', 'White'), ('black', 'Black'), ('blue', 'Blue'), ('brown', 'Brown'), ('tan', 'Tan'), ('white', 'White'), ('yellow', 'Yellow'), ('gray', 'Gray'), ('red', 'Red'), ('orange', 'Orange'), ('green', 'Green')], max_length=50, verbose_name='Primary Color'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='scolor',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('black', 'Black'), ('blue', 'Blue'), ('brown', 'Brown'), ('tan', 'Tan'), ('brindle', 'Brindle'), ('cream', 'Cream/Taupe'), ('gold', 'Gold'), ('gray', 'Gray'), ('red', 'Red'), ('white', 'White'), ('yellow', 'Yellow'), ('black', 'Black'), ('caramel', 'Caramel'), ('chocolate', 'Chocolate'), ('cinnamon', 'Cinnamon'), ('grey', 'Grey'), ('orange', 'Orange'), ('white', 'White'), ('black', 'Black'), ('brown', 'Brown'), ('bay', 'Bay'), ('chestnut', 'Chestnut'), ('grey', 'Grey'), ('white', 'White'), ('black', 'Black'), ('blue', 'Blue'), ('brown', 'Brown'), ('tan', 'Tan'), ('white', 'White'), ('yellow', 'Yellow'), ('gray', 'Gray'), ('red', 'Red'), ('orange', 'Orange'), ('green', 'Green')], max_length=50, verbose_name='Secondary Color'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='size',
            field=models.CharField(blank=True, choices=[('small', 'Small (< 20 lbs)'), ('medium', 'Medium (21 - 60 lbs)'), ('large', 'Large (61 - 110 lbs)'), ('giant', 'Giant (111+ lbs)'), ('small', 'Small ( < 10 lbs)'), ('large', 'Large (10+ lbs)'), ('mini', 'Mini'), ('pony', 'Pony'), ('horse', 'Horse'), ('draft', 'Draft'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10),
        ),
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('animal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.Animal')),
            ],
        ),
    ]
