# Generated by Django 3.1.2 on 2020-10-20 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0006_remove_room_shelter'),
        ('animals', '0009_auto_20200913_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shelter.room'),
        ),
    ]
