# Generated by Django 3.1 on 2020-12-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20201104_1730'),
        ('animals', '0013_auto_20201207_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='owner',
        ),
        migrations.AddField(
            model_name='animal',
            name='owner',
            field=models.ManyToManyField(to='people.Person'),
        ),
    ]
