# Generated by Django 3.1.2 on 2021-01-14 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0006_remove_room_shelter'),
        ('animals', '0013_animal_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shelter.shelter'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='size',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('small', 'Small (< 20 lbs)'), ('medium', 'Medium (21 - 60 lbs)'), ('large', 'Large (61 - 110 lbs)'), ('giant', 'Giant (111+ lbs)'), ('unknown', 'Unknown'), ('small', 'Small ( < 10 lbs)'), ('large', 'Large (10+ lbs)'), ('unknown', 'Unknown'), ('mini', 'Mini'), ('pony', 'Pony'), ('horse', 'Horse'), ('draft', 'Draft'), ('unknown', 'Unknown'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10),
        ),
    ]
