# Generated by Django 3.1.2 on 2021-01-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0014_auto_20210113_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='animal',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=999, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
