# Generated by Django 3.1 on 2020-12-10 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20201104_1730'),
        ('animals', '0014_auto_20201210_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='owner',
        ),
        migrations.AddField(
            model_name='animal',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.person'),
        ),
    ]
