# Generated by Django 3.1 on 2020-12-13 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0012_auto_20201210_1008'),
        ('animals', '0015_auto_20201210_2217'),
    ]

    operations = [
    ]
