# Generated by Django 3.1 on 2020-12-13 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20201104_1730'),
        ('animals', '0016_merge_20201213_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporter', to='people.person'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='owner',
            field=models.ManyToManyField(blank=True, to='people.Person'),
        ),
    ]
