# Generated by Django 3.1.2 on 2021-02-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0016_add_found_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='owner',
            new_name='owners',
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.CharField(blank=True, choices=[('youth', 'Youth'), ('adult', 'Adult'), ('senior', 'Senior'), ('kitten', 'Kitten'), ('youth', 'Youth'), ('adult', 'Adult'), ('senior', 'Senior'), ('geriatric', 'Geriatric'), ('young', 'Young'), ('adult', 'Adult'), ('senior', 'Senior'), ('young', 'Young'), ('adult', 'Adult'), ('senior', 'Senior')], max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'REPORTED'), ('REUNITED', 'REUNITED'), ('EVACUATED', 'EVACUATED'), ('SHELTERED', 'SHELTERED'), ('SHELTERED IN PLACE', 'SHELTERED IN PLACE'), ('UNABLE TO LOCATE', 'UNABLE TO LOCATE'), ('DECEASED', 'DECEASED'), ('CANCELED', 'CANCELED')], default='REPORTED', max_length=20),
        ),
    ]
