# Generated by Django 3.1.2 on 2021-04-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0017_auto_20210202_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='medical_notes',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
