# Generated by Django 3.1.2 on 2021-04-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0018_animal_medical_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='intake_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
