# Generated by Django 3.1.2 on 2021-04-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0019_animal_intake_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='size',
            field=models.CharField(blank=True, choices=[('small', 'Small (< 20 lbs)'), ('medium', 'Medium (21 - 60 lbs)'), ('large', 'Large (61 - 110 lbs)'), ('giant', 'Giant (111+ lbs)'), ('small', 'Small ( < 10 lbs)'), ('large', 'Large (10+ lbs)'), ('mini', 'Mini'), ('pony', 'Pony'), ('horse', 'Horse'), ('draft', 'Draft'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10),
        ),
    ]
