# Generated by Django 3.1.2 on 2022-04-19 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_auto_20220419_1416'),
        ('animals', '0020_auto_20210420_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='aco_required',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('yes', 'Yes'), ('no', 'No')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='pcolor',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('black', 'Black'), ('blue', 'Blue'), ('brown', 'Brown'), ('brindle', 'Brindle'), ('cream', 'Cream/Taupe'), ('gold', 'Gold'), ('gray', 'Gray'), ('harlequin', 'Harlequin'), ('pink', 'Pink'), ('red', 'Red'), ('tan', 'Tan'), ('white', 'White'), ('yellow', 'Yellow'), ('black', 'Black'), ('blue', 'Blue'), ('caramel', 'Caramel'), ('chocolate', 'Chocolate'), ('cinnamon', 'Cinnamon'), ('cream', 'Cream'), ('fawn', 'Fawn'), ('grey', 'Grey'), ('lilac', 'Lilac'), ('orange', 'Orange'), ('red', 'Red'), ('smoke', 'Smoke'), ('white', 'White'), ('black', 'Black'), ('brown', 'Brown'), ('bay', 'Bay'), ('chestnut', 'Chestnut'), ('grey', 'Grey'), ('white', 'White'), ('black', 'Black'), ('blue', 'Blue'), ('brown', 'Brown'), ('tan', 'Tan'), ('white', 'White'), ('yellow', 'Yellow'), ('gray', 'Gray'), ('red', 'Red'), ('orange', 'Orange'), ('green', 'Green')], max_length=50, verbose_name='Primary Color'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporter_animals', to='people.person'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='scolor',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('black', 'Black'), ('blue', 'Blue'), ('brown', 'Brown'), ('brindle', 'Brindle'), ('cream', 'Cream/Taupe'), ('gold', 'Gold'), ('gray', 'Gray'), ('harlequin', 'Harlequin'), ('pink', 'Pink'), ('red', 'Red'), ('tan', 'Tan'), ('white', 'White'), ('yellow', 'Yellow'), ('black', 'Black'), ('blue', 'Blue'), ('caramel', 'Caramel'), ('chocolate', 'Chocolate'), ('cinnamon', 'Cinnamon'), ('cream', 'Cream'), ('fawn', 'Fawn'), ('grey', 'Grey'), ('lilac', 'Lilac'), ('orange', 'Orange'), ('red', 'Red'), ('smoke', 'Smoke'), ('white', 'White'), ('black', 'Black'), ('brown', 'Brown'), ('bay', 'Bay'), ('chestnut', 'Chestnut'), ('grey', 'Grey'), ('white', 'White'), ('black', 'Black'), ('blue', 'Blue'), ('brown', 'Brown'), ('tan', 'Tan'), ('white', 'White'), ('yellow', 'Yellow'), ('gray', 'Gray'), ('red', 'Red'), ('orange', 'Orange'), ('green', 'Green')], max_length=50, verbose_name='Secondary Color'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='size',
            field=models.CharField(blank=True, choices=[('small', 'Small (< 20 lbs)'), ('medium', 'Medium (21 - 60 lbs)'), ('large', 'Large (61 - 110 lbs)'), ('giant', 'Giant (111+ lbs)'), ('small', 'Small ( < 10 lbs)'), ('large', 'Large (10+ lbs)'), ('mini', 'Mini'), ('pony', 'Pony'), ('standard', 'Standard'), ('draft', 'Draft'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='state',
            field=models.CharField(blank=True, choices=[('AL', 'AL'), ('AK', 'AK'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('VA', 'VA'), ('VT', 'VT'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY')], max_length=2),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'REPORTED'), ('REUNITED', 'REUNITED'), ('SHELTERED', 'SHELTERED'), ('SHELTERED IN PLACE', 'SHELTERED IN PLACE'), ('UNABLE TO LOCATE', 'UNABLE TO LOCATE'), ('DECEASED', 'DECEASED'), ('CANCELED', 'CANCELED')], default='REPORTED', max_length=20),
        ),
    ]
