# Generated by Django 3.2.14 on 2023-04-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0024_auto_20221111_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='microchip',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='behavior_notes',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='animal',
            name='medical_notes',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
