# Generated by Django 3.2.14 on 2023-06-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0025_auto_20230421_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'REPORTED'), ('REPORTED (EVACUATION)', 'REPORTED (EVACUATION)'), ('REPORTED (SHELTERED IN PLACE)', 'REPORTED (SHELTERED IN PLACE)'), ('REUNITED', 'REUNITED'), ('SHELTERED', 'SHELTERED'), ('SHELTERED IN PLACE', 'SHELTERED IN PLACE'), ('UNABLE TO LOCATE', 'UNABLE TO LOCATE'), ('NO FURTHER ACTION', 'NO FURTHER ACTION'), ('DECEASED', 'DECEASED'), ('CANCELED', 'CANCELED')], default='REPORTED', max_length=30),
        ),
    ]
