# Generated by Django 3.2.14 on 2023-07-04 14:53

from django.db import migrations, models


def update_status_change(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Animal = apps.get_model("animals", "Animal")
    Animal.objects.using(db_alias).filter(status="REPORTED (SHELTERED IN PLACE)").update(status="REPORTED (SIP REQUESTED)")
    Animal.objects.using(db_alias).filter(status="REPORTED (EVACUATION)").update(status="REPORTED (EVAC REQUESTED)")

class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0026_alter_animal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'REPORTED'), ('REPORTED (EVAC REQUESTED)', 'REPORTED (EVAC REQUESTED)'), ('REPORTED (SIP REQUESTED)', 'REPORTED (SIP REQUESTED)'), ('REUNITED', 'REUNITED'), ('SHELTERED', 'SHELTERED'), ('SHELTERED IN PLACE', 'SHELTERED IN PLACE'), ('UNABLE TO LOCATE', 'UNABLE TO LOCATE'), ('NO FURTHER ACTION', 'NO FURTHER ACTION'), ('DECEASED', 'DECEASED'), ('CANCELED', 'CANCELED')], default='REPORTED', max_length=30),
        ),
        migrations.RunPython(update_status_change)
    ]
