# Generated by Django 3.2.14 on 2023-12-20 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0029_create_default_species'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'Species'},
        ),
        migrations.AlterModelOptions(
            name='speciescategory',
            options={'verbose_name_plural': 'Species categories'},
        ),
        migrations.RemoveField(
            model_name='animal',
            name='species',
        ),
    ]
