# Generated by Django 3.2.14 on 2024-03-25 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0018_remove_medicalrecord_patient'),
        ('animals', '0032_alter_species_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='medical_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient', to='vet.medicalrecord'),
        ),
    ]
