# Generated by Django 3.2.14 on 2024-04-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0033_animal_medical_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='id_for_incident',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
