# Generated by Django 3.2.14 on 2025-02-14 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0036_auto_20241101_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='animal',
            name='order',
        ),
    ]
