# Generated by Django 3.2.18 on 2025-03-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0037_auto_20250214_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='sip_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
