# Generated by Django 2.1.11 on 2019-11-03 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacteam',
            name='callsign',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evacteam',
            name='team_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
