# Generated by Django 3.1.2 on 2021-03-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201114_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelterlyuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='shelterlyuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
