# Generated by Django 3.1.2 on 2022-05-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210311_1031'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shelterlyuser',
            managers=[
            ],
        ),
    ]
