# Generated by Django 3.1.2 on 2022-06-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220510_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelterlyuser',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shelterlyuser',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
