# Generated by Django 3.2.14 on 2022-08-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220602_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelterlyuser',
            options={'ordering': ('last_name',)},
        ),
        migrations.AddField(
            model_name='shelterlyuser',
            name='incident_perms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shelterlyuser',
            name='user_perms',
            field=models.BooleanField(default=False),
        ),
    ]
