# Generated by Django 3.2.14 on 2023-08-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20230315_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('short_name', models.CharField(blank=True, max_length=40, null=True)),
                ('liability_name', models.CharField(max_length=80)),
                ('liability_short_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterModelOptions(
            name='shelterlyuser',
            options={'ordering': ('last_name', 'first_name')},
        ),
    ]
