# Generated by Django 3.2.14 on 2023-11-11 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20230812_1516'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
