# Generated by Django 3.2.14 on 2023-11-21 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0007_incident_organization'),
        ('accounts', '0011_shelterlyuser_organizations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelterlyuser',
            name='email_notification',
        ),
        migrations.RemoveField(
            model_name='shelterlyuser',
            name='incident_perms',
        ),
        migrations.RemoveField(
            model_name='shelterlyuser',
            name='organizations',
        ),
        migrations.RemoveField(
            model_name='shelterlyuser',
            name='user_perms',
        ),
        migrations.CreateModel(
            name='ShelterlyUserOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_perms', models.BooleanField(default=False)),
                ('incident_perms', models.BooleanField(default=False)),
                ('email_notification', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_perms', to='incident.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='shelterlyuser',
            name='organization',
            field=models.ManyToManyField(related_name='users', through='accounts.ShelterlyUserOrg', to='incident.Organization'),
        ),
    ]
