# Generated by Django 3.2.14 on 2023-12-20 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0008_auto_20231206_1109'),
        ('accounts', '0014_remove_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelterlyuser',
            name='vet_perms',
        ),
        migrations.AddField(
            model_name='shelterlyuserorg',
            name='vet_perms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shelterlyuserorg',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incident.organization'),
        ),
        migrations.AlterField(
            model_name='shelterlyuserorg',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perms', to=settings.AUTH_USER_MODEL),
        ),
    ]
