# Generated by Django 3.2.14 on 2024-04-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20231220_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelterlyuserorg',
            name='access_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
