# Generated by Django 3.2.14 on 2024-05-29 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_shelterlyuserorg_access_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelterlyuserorg',
            name='email_notification',
        ),
    ]
