# Generated by Django 3.2.14 on 2022-11-11 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0024_auto_20221111_0831'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.animal')),
            ],
        ),
        migrations.CreateModel(
            name='VetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.DateTimeField(auto_now_add=True)),
                ('assigned', models.DateTimeField(blank=True, null=True)),
                ('closed', models.DateTimeField(blank=True, null=True)),
                ('concern', models.CharField(max_length=20)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('when_available', 'When Available')], default='urgent', max_length=25)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.animal')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_admin_time', models.DateTimeField(blank=True, null=True)),
                ('actual_admin_time', models.DateTimeField(blank=True, null=True)),
                ('treatment_description', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=20)),
                ('unit', models.CharField(choices=[('ml', 'ml'), ('cap', 'cap'), ('tab', 'tab')], default='ml', max_length=25)),
                ('route', models.CharField(choices=[('IV', 'IV'), ('SQ', 'SQ'), ('PO', 'PO')], default='IV', max_length=25)),
                ('treatment_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vet.treatmentplan')),
            ],
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='vet_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vet.vetrequest'),
        ),
    ]
