# Generated by Django 3.2.14 on 2022-12-30 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='name',
            new_name='description',
        ),
        migrations.AddField(
            model_name='treatment',
            name='valid_routes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='valid_units',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentrequest',
            name='treatment_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vet.treatmentplan'),
        ),
    ]
