# Generated by Django 3.1.2 on 2022-06-18 11:59

from django.db import migrations

complaints = ['Painful', 'Not eating', 'Vomiting/diarrhea', 'Diarrhea', 'Lameness', 'Trauma/wounds', 'Facial Swelling',
              'Burns', 'Pale gums', 'Lethargic', 'Collapse', 'Abnormal behavior', 'Eye/ear problems', 'Difficulty breathing',
              'Labored breathing']

diagnoses = ['Apparently healthy', 'Gatrointestinal problem', 'Parvovirus', 'Stress colotis', 'Intestinal parasites', 'Pancreatits',
             'Burns', 'Wound/laceration', 'Abrasions', 'Fracture', 'CCL rupture', 'Ectoparasites', 'Corneal ulcer', 'Stromal abscess',
             'Uveitis (no ulcer)', 'Congestive heart failure', 'Smoke inhalation', 'Pneumonia', 'Asthma', 'Hemothorax', 'Ascites',
             'Allergic reaction', 'Dermatitis', 'Diaetes mellitus', 'OPEN', 'Other', 'Shock', 'Dehydration', 'Recumbency', 'Mastitis', 'Dytocia/abortion',
             'Uterine prolapse', 'Rectal prolapse', 'Sepsis', "Equine Cushing's/pituitary pars intermedia dysfunction (PPID)",
             'Equine metabolic syndrome', 'Laminitis', 'Renal failure', 'Hepatic lipidosis', 'Hyperparathyroidism', 'Foreign body/fistula',
             'Abscess', 'Lymphangitis']

def create_fixtures(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    PresentingComplaint = apps.get_model("vet", "PresentingComplaint")
    for complaint in complaints:
        PresentingComplaint.objects.using(db_alias).create(name=complaint)

    Diagnosis = apps.get_model("vet", "Diagnosis")
    for diagnosis in diagnoses:
        Diagnosis.objects.using(db_alias).create(name=diagnosis)

class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_fixtures)
    ]
