# Generated by Django 3.2.14 on 2023-12-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0002_fixtures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetrequest',
            name='concern',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
