# Generated by Django 3.2.14 on 2023-12-28 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0005_populate_exam_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vetrequest',
            old_name='other_diagnosis',
            new_name='diagnosis_other',
        ),
        migrations.AddField(
            model_name='exam',
            name='open',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vetrequest',
            name='diagnosis_notes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.RemoveField(
            model_name='vetrequest',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='vetrequest',
            name='diagnosis',
            field=models.ManyToManyField(to='vet.Diagnosis'),
        ),
    ]
