# Generated by Django 3.2.14 on 2024-01-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0008_more_fixtures'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetrequest',
            name='diagnostics_notes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='vetrequest',
            name='diagnostics_other',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vetrequest',
            name='diagnosis_other',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vetrequest',
            name='diagnostics',
            field=models.ManyToManyField(blank=True, to='vet.Diagnostic'),
        ),
        migrations.AlterField(
            model_name='vetrequest',
            name='procedures',
            field=models.ManyToManyField(blank=True, to='vet.Procedure'),
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'ordering': ('category', 'description')},
        ),
        migrations.AddField(
            model_name='vetrequest',
            name='procedure_notes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='vetrequest',
            name='procedure_other',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
