# Generated by Django 3.2.14 on 2024-01-04 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vet', '0009_auto_20240103_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='weight_estimated',
            field=models.BooleanField(default=False),
        ),
    ]
