# Generated by Django 3.2.14 on 2024-01-04 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0032_alter_species_options'),
        ('vet', '0010_auto_20240104_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetrequest',
            name='requested',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='vetrequest',
            name='assigned',
        ),
        migrations.RemoveField(
            model_name='vetrequest',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='vetrequest',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='vetrequest',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='vetrequest',
            name='diagnosis_notes',
        ),
        migrations.RemoveField(
            model_name='vetrequest',
            name='diagnosis_other',
        ),
        migrations.RemoveField(
            model_name='vetrequest',
            name='diagnostics',
        ),
        migrations.RemoveField(
            model_name='vetrequest',
            name='diagnostics_notes',
        ),
        migrations.RemoveField(
            model_name='vetrequest',
            name='diagnostics_other',
        ),
        migrations.RemoveField(
            model_name='vetrequest',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='vetrequest',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='vetrequest',
            name='procedure_notes',
        ),
        migrations.RemoveField(
            model_name='vetrequest',
            name='procedure_other',
        ),
        migrations.RemoveField(
            model_name='vetrequest',
            name='procedures',
        ),
        migrations.RemoveField(
            model_name='vetrequest',
            name='status',
        ),
        migrations.AlterField(
            model_name='exam',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_other', models.CharField(blank=True, max_length=50, null=True)),
                ('procedure_notes', models.CharField(blank=True, max_length=300, null=True)),
                ('diagnostics_other', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnostics_notes', models.CharField(blank=True, max_length=300, null=True)),
                ('diagnosis_other', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnosis_notes', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(default='Open', max_length=20)),
                ('diagnosis', models.ManyToManyField(blank=True, to='vet.Diagnosis')),
                ('diagnostics', models.ManyToManyField(blank=True, to='vet.Diagnostic')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vet.exam')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='animals.animal')),
                ('procedures', models.ManyToManyField(blank=True, to='vet.Procedure')),
            ],
        ),
        migrations.AddField(
            model_name='vetrequest',
            name='medical_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vet.medicalrecord'),
        ),
    ]
