# Generated by Django 3.2.14 on 2024-01-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0012_auto_20240104_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentplan',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='route',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='unit',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
