# Generated by Django 3.2.14 on 2024-01-08 20:50
from django.conf import settings

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0013_auto_20240107_0702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='examquestion',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='diagnostics',
        ),
        migrations.AddField(
            model_name='diagnosticresult',
            name='complete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresult',
            name='open',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='diagnostics_other',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='procedure_other',
        ),
        migrations.AddField(
            model_name='diagnosticresult',
            name='other_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='presentingcomplaint',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='procedures',
        ),
        migrations.AlterField(
            model_name='diagnosticresult',
            name='notes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticresult',
            name='result',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ProcedureResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.DateTimeField(auto_now_add=True)),
                ('complete', models.DateTimeField(blank=True, null=True)),
                ('performer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('other_name', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('medical_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vet.medicalrecord')),
                ('procedure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vet.procedure')),
            ],
        ),
    ]
