# Generated by Django 3.2.14 on 2024-02-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0016_auto_20240131_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examanswer',
            options={'ordering': ('question__id',)},
        ),
        migrations.AddField(
            model_name='exam',
            name='medical_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentrequest',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vetrequest',
            name='complaints_other',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='respiratory_rate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='procedureresult',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
