# Generated by Django 3.2.14 on 2024-09-01 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0019_auto_20240828_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentrequest',
            name='medical_record',
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='medical_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vet.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='treatmentrequest',
            name='treatment_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vet.treatmentplan'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='route',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='unit',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
