# Generated by Django 3.2.14 on 2024-09-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0020_auto_20240901_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentplan',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='route',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='unit',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
