# Generated by Django 3.2.14 on 2024-09-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0020_auto_20240901_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatmentrequest',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
