# Generated by Django 3.2.14 on 2024-09-25 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0021_auto_20240921_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='medical_plan',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='medical_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MedicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('medical_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vet.medicalrecord')),
            ],
        ),
    ]
