# Generated by Django 3.2.14 on 2024-09-30 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0022_auto_20240925_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalnote',
            name='open',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
