# Generated by Django 3.2.18 on 2024-11-14 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0023_medicalnote_open'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalnote',
            options={'ordering': ('-open',)},
        ),
        migrations.CreateModel(
            name='MedicalRecordImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(blank=True, max_length=25)),
                ('medical_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vet.medicalrecord')),
            ],
        ),
    ]
