# Generated by Django 3.2.14 on 2024-12-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0024_auto_20241113_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentplan',
            name='route',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
