# Generated by Django 3.1.2 on 2022-06-18 11:59

from django.db import migrations


def create_test_fixture(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Incident = apps.get_model("incident", "Incident")
    Incident.objects.using(db_alias).create(name="Test", slug="test", latitude=0, longitude=0)

class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_test_fixture)
    ]
