# Generated by Django 3.2.14 on 2022-08-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_auto_20220618_0459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='incident',
            name='latitude',
            field=models.DecimalField(decimal_places=4, max_digits=9),
        ),
        migrations.AlterField(
            model_name='incident',
            name='longitude',
            field=models.DecimalField(decimal_places=4, max_digits=9),
        ),
    ]
