# Generated by Django 3.2.14 on 2022-10-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0003_auto_20220808_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='slug',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
