# Generated by Django 3.2.14 on 2023-07-04 14:53

from django.db import migrations, models


def default_org(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Organization = apps.get_model("incident", "Organization")
    Incident = apps.get_model("incident", "Incident")
    default_org = Organization.objects.using(db_alias).create(name='Change Me', slug='changeme', liability_name='Change Me', liability_short_name='CHANGEME')
    Incident.objects.using(db_alias).all().update(organization=default_org)

class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0006_incident_organization'),
    ]

    operations = [
        migrations.RunPython(default_org, migrations.RunPython.noop)
    ]
