# Generated by Django 3.2.14 on 2023-12-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0007_default_orgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='training',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
