# Generated by Django 3.2.14 on 2023-11-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0007_incident_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.CharField(default='changeme', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
