# Generated by Django 3.2.18 on 2024-04-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0008_auto_20231206_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
