# Generated by Django 3.2.14 on 2024-05-08 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0009_add_hide_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryAccess',
            fields=[
                ('id', models.UUIDField(default='0dc639736f5e4b30a8ee5368e8c099b9', editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_expires_at', models.DateField()),
                ('link_expires_at', models.DateField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.organization')),
            ],
        ),
    ]
