# Generated by Django 3.2.14 on 2024-05-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0010_temporaryaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='short_name',
            field=models.CharField(default='changeme', max_length=10),
        ),
        migrations.AlterField(
            model_name='temporaryaccess',
            name='access_expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temporaryaccess',
            name='id',
            field=models.UUIDField(default='4fec389bbe5e494f9c739f61a48a3ccc', editable=False, primary_key=True, serialize=False),
        ),
    ]
