# Generated by Django 3.2.14 on 2024-06-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0012_auto_20240529_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='slug',
            field=models.CharField(max_length=20),
        ),
    ]
