# Generated by Django 3.2.18 on 2024-06-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0013_alter_incident_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='caltopo_map_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='watchduty_map_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
