# Generated by Django 3.2.18 on 2024-10-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0014_auto_20240620_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='caltopo_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='watchduty_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
