# Generated by Django 3.2.18 on 2025-02-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0015_auto_20240930_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='default_followup_days',
            field=models.IntegerField(default=1),
        ),
    ]
