# Generated by Django 3.2.18 on 2025-04-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0016_incident_default_followup_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='verbal_liability_text',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
