# Generated by Django 3.2.14 on 2025-04-23 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0016_incident_default_followup_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='incident.organization'),
            preserve_default=False,
        ),
    ]
