# Generated by Django 3.2.18 on 2025-04-23 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0017_alter_incident_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='organization',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='incident.organization'),
        ),
    ]
