# Generated by Django 2.1.11 on 2019-11-19 03:37

from django.db import migrations, models
import form_utils


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[form_utils.PHONE_VALIDATOR]),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=50, validators=[form_utils.NAME_VALIDATOR]),
        ),
        migrations.AlterField(
            model_name='person',
            name='home_phone',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[form_utils.PHONE_VALIDATOR]),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=50, validators=[form_utils.NAME_VALIDATOR]),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_phone',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[form_utils.PHONE_VALIDATOR]),
        ),
    ]
