# Generated by Django 3.0.4 on 2020-04-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20191119_0337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
