# Generated by Django 3.0.5 on 2020-04-13 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20191119_0337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='cell_phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='person',
            name='home_phone',
        ),
        migrations.RemoveField(
            model_name='person',
            name='work_phone',
        ),
    ]
