# Generated by Django 2.1.7 on 2019-05-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0002_remove_evacreq_worker'),
        ('people', '0005_auto_20190425_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('cell_phone', models.CharField(max_length=50)),
                ('agency_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={},
        ),
    ]
