# Generated by Django 2.1.7 on 2019-05-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20190511_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='reporter',
        ),
    ]
