# Generated by Django 3.0.8 on 2020-07-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20200515_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='agency',
            field=models.TextField(blank=True),
        ),
    ]
