# Generated by Django 3.1.2 on 2020-12-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_personchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
