# Generated by Django 3.1.2 on 2021-01-19 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0014_auto_20210119_1503'),
        ('people', '0011_auto_20201229_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_contact_time', models.DateTimeField()),
                ('owner_contact_note', models.TextField()),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
            ],
        ),
    ]
