# Generated by Django 3.1.2 on 2021-01-31 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evac', '0008_auto_20210131_0945'),
        ('hotline', '0013_remove_visitnote_owner_contacted'),
        ('people', '0012_ownercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownercontact',
            name='evac_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evac.evacassignment'),
        ),
        migrations.AddField(
            model_name='ownercontact',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotline.servicerequest'),
        ),
    ]
