# Generated by Django 3.1.2 on 2021-04-20 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_auto_20210131_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('-first_name',)},
        ),
        migrations.RemoveField(
            model_name='ownercontact',
            name='evac_assignment',
        ),
    ]
