# Generated by Django 3.1.2 on 2021-04-26 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_auto_20210420_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownercontact',
            options={'ordering': ('-owner_contact_time',)},
        ),
    ]
