# Generated by Django 3.1.2 on 2022-02-11 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_auto_20210426_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownercontact',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.person'),
        ),
        migrations.AlterField(
            model_name='ownercontact',
            name='owner_contact_time',
            field=models.DateTimeField(null=True),
        ),
    ]
