# Generated by Django 3.2.14 on 2023-12-06 21:36

from django.db import migrations, models
import django.db.models.deletion
import people.models

class Migration(migrations.Migration):

    dependencies = [
        ('people', '0019_auto_20220602_0851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('first_name',)},
        ),
        migrations.AddField(
            model_name='person',
            name='incident',
            field=models.ForeignKey(default=people.models.test_incident, on_delete=django.db.models.deletion.CASCADE, to='incident.incident'),
        ),
    ]
