# Generated by Django 2.1.7 on 2019-05-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0006_auto_20190511_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvacTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evac_team_members', models.ManyToManyField(to='people.TeamMember')),
            ],
        ),
    ]
