# Generated by Django 2.1.11 on 2019-11-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvacTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evac_team_members', models.ManyToManyField(to='evac.EvacTeamMember')),
            ],
        ),
    ]
