# Generated by Django 3.1.2 on 2020-10-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0006_auto_20200828_1632'),
        ('evac', '0003_auto_20200416_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvacAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('service_requests', models.ManyToManyField(to='hotline.ServiceRequest')),
            ],
        ),
        migrations.CreateModel(
            name='EvacTeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('agency_id', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.DeleteModel(
            name='EvacTeam',
        ),
        migrations.AddField(
            model_name='evacassignment',
            name='team_members',
            field=models.ManyToManyField(to='evac.EvacTeamMember'),
        ),
    ]
