# Generated by Django 3.0.8 on 2020-08-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evac', '0004_auto_20200830_0231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evacteammember',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='evacteammember',
            name='agency_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evacteammember',
            name='last_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
