# Generated by Django 3.1.2 on 2020-11-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evac', '0005_visitnote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitNote',
        ),
    ]
