# Generated by Django 3.0.8 on 2020-09-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evac', '0005_auto_20200830_0254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evacteammember',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterField(
            model_name='evacassignment',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evacteammember',
            name='agency_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='evacteammember',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
