# Generated by Django 3.1.2 on 2020-12-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0013_auto_20201218_0618'),
        ('hotline', '0010_auto_20201210_1008'),
        ('evac', '0006_delete_visitnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacassignment',
            name='animals',
            field=models.ManyToManyField(to='animals.Animal'),
        ),
        migrations.AlterField(
            model_name='evacassignment',
            name='service_requests',
            field=models.ManyToManyField(related_name='evacuation_assignments', to='hotline.ServiceRequest'),
        ),
    ]
