# Generated by Django 3.1.2 on 2021-01-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0016_add_found_location'),
        ('evac', '0007_auto_20201218_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evacassignment',
            name='animals',
            field=models.ManyToManyField(blank=True, related_name='evacuation_assignments', to='animals.Animal'),
        ),
    ]
