# Generated by Django 3.1.2 on 2021-04-20 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0016_auto_20210420_1128'),
        ('people', '0014_auto_20210420_1128'),
        ('evac', '0010_dispatchteam_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatchteam',
            options={'ordering': ['-dispatch_date']},
        ),
        migrations.RemoveField(
            model_name='evacassignment',
            name='animals',
        ),
        migrations.RemoveField(
            model_name='evacassignment',
            name='service_requests',
        ),
    ]
