# Generated by Django 3.1.2 on 2021-09-13 18:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evac', '0014_auto_20210426_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedrequest',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignedrequest',
            name='dispatch_assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='evac.evacassignment'),
        ),
    ]
