# Generated by Django 3.1.2 on 2022-04-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evac', '0015_auto_20210913_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatchteam',
            options={},
        ),
        migrations.AlterField(
            model_name='assignedrequest',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
