# Generated by Django 3.1.2 on 2022-05-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evac', '0016_auto_20220421_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchteam',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evacteammember',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
