# Generated by Django 3.2.14 on 2025-03-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evac', '0024_evacassignment_dispatch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evacassignment',
            name='dispatch_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
