# Generated by Django 3.2.14 on 2025-04-16 14:00

from django.db import migrations, models


def trunctate_agency_id(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    EvacTeamMember = apps.get_model("evac", "EvacTeamMember")

    for member in EvacTeamMember.objects.using(db_alias).all():
        if member.agency_id:
            member.agency_id = member.agency_id[:20]
            member.save()

class Migration(migrations.Migration):

    dependencies = [
        ('evac', '0025_alter_evacassignment_dispatch_date'),
    ]

    operations = [
        migrations.RunPython(trunctate_agency_id, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='evacteammember',
            name='agency_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
