# Generated by Django 3.2.14 on 2025-04-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evac', '0026_alter_evacteammember_agency_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedrequest',
            name='followup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
