# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push]
defaults:
  run:
    working-directory: ./frontend
env:
  CI: false
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm config set "@fortawesome:registry" https://npm.fontawesome.com/
    - run: npm config set "//npm.fontawesome.com/:_authToken" ${{ secrets.FA_PRO_KEY }}
    - run: npm cache clean --force
    - run: rm -rf node_modules package-lock.json
    - run: npm install
    - run: npm run build --if-present
    - run: npm run test:coverage-ci
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: "d2227d27-a134-4fbf-902c-d13b9a11cf3f"
